spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shortly
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
#
#spring.datasource.username=
#spring.datasource.password=
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=
#spring.jpa.properties.hibernate.format_sql=true
