spring:
  application:
    name: read-api
  data:
    rest:
      base-path: /api
  datasource:
    url: jdbc:postgresql://localhost:5432/shortly
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    ddl-auto: create-drop